language: python
python:
  - "3.7"
script: # stolen from https://github.com/appu1232/Discord-Selfbot/blob/master/.travis.yml
  - python -m compileall ./main.py
  - python -m compileall ./addons
  - python ./main.py --test-run 
